

uc_pets_rn50:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50/perturbation
  ae_folder: output/uc_pets_rn50/ae
  
  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 5e-5
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/pets_rn50_cluster10.pth
  output_dir: output/uc_pets_rn50/perturbation
  batch_size: 32

uc_pets_rn50_32:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50_32/perturbation
  ae_folder: output/uc_pets_rn50_32/ae
  
  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 5e-5
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/pets_rn50_cluster10.pth
  output_dir: output/uc_pets_rn50_32/perturbation
  batch_size: 32

uc_pets_rn50_64:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50_64/perturbation
  ae_folder: output/uc_pets_rn50_64/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/pets_rn50_cluster10.pth
  output_dir: output/uc_pets_rn50_64/perturbation
  batch_size: 64

uc_pets_rn50_128:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50_128/perturbation
  ae_folder: output/uc_pets_rn50_128/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/pets_rn50_cluster10.pth
  output_dir: output/uc_pets_rn50_128/perturbation
  batch_size: 128

uc_pets_rn50_256:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50_256/perturbation
  ae_folder: output/uc_pets_rn50_256/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/pets_rn50_cluster10.pth
  output_dir: output/uc_pets_rn50_256/perturbation
  batch_size: 256

uc_pets_rn50_512:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50_512/perturbation
  ae_folder: output/uc_pets_rn50_512/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/pets_rn50_cluster10.pth
  output_dir: output/uc_pets_rn50_512/perturbation
  batch_size: 512

uc_pets_rn50_1024:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50_1024/perturbation
  ae_folder: output/uc_pets_rn50_1024/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/pets_rn50_cluster10.pth
  output_dir: output/uc_pets_rn50_1024/perturbation
  batch_size: 1024

uc_medmnist_rn50:
  data_config: config/data.yaml
  dataset: medmnist
  perturbation_dir: output/uc_medmnist_rn50/perturbation
  ae_folder: output/uc_medmnist_rn50/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/medmnist_rn50_cluster3.pth
  output_dir: output/uc_medmnist_rn50/perturbation
  batch_size: 32

uc_bloodmnist_rn50_32:
  data_config: config/data.yaml
  dataset: bloodmnist
  perturbation_dir: output/uc_bloodmnist_rn50_32/perturbation
  ae_folder: output/uc_bloodmnist_rn50_32/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/bloodmnist_rn50_cluster3.pth
  output_dir: output/uc_bloodmnist_rn50_32/perturbation
  batch_size: 32

uc_bloodmnist_rn50_64:
  data_config: config/data.yaml
  dataset: bloodmnist
  perturbation_dir: output/uc_bloodmnist_rn50_64/perturbation
  ae_folder: output/uc_bloodmnist_rn50_64/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/bloodmnist_rn50_cluster3.pth
  output_dir: output/uc_bloodmnist_rn50_64/perturbation
  batch_size: 64

uc_bloodmnist_rn50_128:
  data_config: config/data.yaml
  dataset: bloodmnist
  perturbation_dir: output/uc_bloodmnist_rn50_128/perturbation
  ae_folder: output/uc_bloodmnist_rn50_128/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/bloodmnist_rn50_cluster3.pth
  output_dir: output/uc_bloodmnist_rn50_128/perturbation
  batch_size: 128

uc_bloodmnist_rn50_256:
  data_config: config/data.yaml
  dataset: bloodmnist
  perturbation_dir: output/uc_bloodmnist_rn50_256/perturbation
  ae_folder: output/uc_bloodmnist_rn50_256/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/bloodmnist_rn50_cluster3.pth
  output_dir: output/uc_bloodmnist_rn50_256/perturbation
  batch_size: 256

uc_bloodmnist_rn50_512:
  data_config: config/data.yaml
  dataset: bloodmnist
  perturbation_dir: output/uc_bloodmnist_rn50_512/perturbation
  ae_folder: output/uc_bloodmnist_rn50_512/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/bloodmnist_rn50_cluster3.pth
  output_dir: output/uc_bloodmnist_rn50_512/perturbation
  batch_size: 512

uc_pathmnist_rn50_32:
  data_config: config/data.yaml
  dataset: pathmnist
  perturbation_dir: output/uc_pathmnist_rn50_32/perturbation
  ae_folder: output/uc_pathmnist_rn50_32/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/pathmnist_rn50_cluster3.pth
  output_dir: output/uc_pathmnist_rn50_32/perturbation
  batch_size: 32

uc_pathmnist_rn50_64:
  data_config: config/data.yaml
  dataset: pathmnist
  perturbation_dir: output/uc_pathmnist_rn50_64/perturbation
  ae_folder: output/uc_pathmnist_rn50_64/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/pathmnist_rn50_cluster3.pth
  output_dir: output/uc_pathmnist_rn50_64/perturbation
  batch_size: 64


uc_pathmnist_rn50_128:
  data_config: config/data.yaml
  dataset: pathmnist
  perturbation_dir: output/uc_pathmnist_rn50_128/perturbation
  ae_folder: output/uc_pathmnist_rn50_128/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/pathmnist_rn50_cluster3.pth
  output_dir: output/uc_pathmnist_rn50_128/perturbation
  batch_size: 128


uc_pathmnist_rn50_256:
  data_config: config/data.yaml
  dataset: pathmnist
  perturbation_dir: output/uc_pathmnist_rn50_256/perturbation
  ae_folder: output/uc_pathmnist_rn50_256/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/pathmnist_rn50_cluster3.pth
  output_dir: output/uc_pathmnist_rn50_256/perturbation
  batch_size: 256


uc_pathmnist_rn50_512:
  data_config: config/data.yaml
  dataset: pathmnist
  perturbation_dir: output/uc_pathmnist_rn50_512/perturbation
  ae_folder: output/uc_pathmnist_rn50_512/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/pathmnist_rn50_cluster3.pth
  output_dir: output/uc_pathmnist_rn50_512/perturbation
  batch_size: 512


uc_pcam_rn50:
  data_config: config/data.yaml
  dataset: pcam
  perturbation_dir: output/uc_pcam_rn50/perturbation
  ae_folder: output/uc_pcam_rn50/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 30
  target_offset: 1
  norm: linf

  cluster: output/cluster/pcam_rn50_cluster3.pth
  output_dir: output/uc_pcam_rn50/perturbation

uc_flowers_rn50_32:
  data_config: config/data.yaml
  dataset: flowers
  perturbation_dir: output/uc_flowers_rn50_32/perturbation
  ae_folder: output/uc_flowers_rn50_32/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers_rn50_cluster3.pth
  output_dir: output/uc_flowers_rn50_32/perturbation
  batch_size: 32

uc_flowers_rn50_64:
  data_config: config/data.yaml
  dataset: flowers
  perturbation_dir: output/uc_flowers_rn50_64/perturbation
  ae_folder: output/uc_flowers_rn50_64/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers_rn50_cluster3.pth
  output_dir: output/uc_flowers_rn50_64/perturbation
  batch_size: 64

uc_flowers_rn50_128:
  data_config: config/data.yaml
  dataset: flowers
  perturbation_dir: output/uc_flowers_rn50_128/perturbation
  ae_folder: output/uc_flowers_rn50_128/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers_rn50_cluster3.pth
  output_dir: output/uc_flowers_rn50_128/perturbation
  batch_size: 128

uc_flowers_rn50_256:
  data_config: config/data.yaml
  dataset: flowers
  perturbation_dir: output/uc_flowers_rn50_256/perturbation
  ae_folder: output/uc_flowers_rn50_256/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers_rn50_cluster3.pth
  output_dir: output/uc_flowers_rn50_256/perturbation
  batch_size: 256

uc_flowers_rn50_512:
  data_config: config/data.yaml
  dataset: flowers
  perturbation_dir: output/uc_flowers_rn50_512/perturbation
  ae_folder: output/uc_flowers_rn50_512/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers_rn50_cluster3.pth
  output_dir: output/uc_flowers_rn50_512/perturbation
  batch_size: 512

uc_organamnist_rn50:
  data_config: config/data.yaml
  dataset: organamnist
  perturbation_dir: output/uc_organamnist_rn50/perturbation
  ae_folder: output/uc_organamnist_rn50/ae

  model: RN50_gray
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: gray
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/organamnist_rn50_cluster3.pth
  output_dir: output/uc_organamnist_rn50/perturbation

uc_flowers102_rn50_32:
  data_config: config/data.yaml
  dataset: flowers102
  perturbation_dir: output/uc_flowers102_rn50_32/perturbation
  ae_folder: output/uc_flowers102_rn50_32/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers102_rn50_cluster5.pth
  output_dir: output/uc_flowers102_rn50_32/perturbation
  batch_size: 32

uc_flowers102_rn50_64:
  data_config: config/data.yaml
  dataset: flowers102
  perturbation_dir: output/uc_flowers102_rn50_64/perturbation
  ae_folder: output/uc_flowers102_rn50_64/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers102_rn50_cluster5.pth
  output_dir: output/uc_flowers102_rn50_64/perturbation
  batch_size: 64

 
uc_flowers102_rn50_128:
  data_config: config/data.yaml
  dataset: flowers102
  perturbation_dir: output/uc_flowers102_rn50_128/perturbation
  ae_folder: output/uc_flowers102_rn50_128/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers102_rn50_cluster5.pth
  output_dir: output/uc_flowers102_rn50_128/perturbation
  batch_size: 128

uc_flowers102_rn50_256:
  data_config: config/data.yaml
  dataset: flowers102
  perturbation_dir: output/uc_flowers102_rn50_256/perturbation
  ae_folder: output/uc_flowers102_rn50_256/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers102_rn50_cluster5.pth
  output_dir: output/uc_flowers102_rn50_256/perturbation
  batch_size: 256

uc_flowers102_rn50_512:
  data_config: config/data.yaml
  dataset: flowers102
  perturbation_dir: output/uc_flowers102_rn50_512/perturbation
  ae_folder: output/uc_flowers102_rn50_512/ae

  model: RN50
  checkpoint: checkpoints/RN50_imagenet.pth
  normalize: imagenet
  num_classes: 1000

  epsilon: 16
  lr: 1e-4
  num_epoch: 50
  target_offset: 1
  norm: linf

  cluster: output/cluster/flowers102_rn50_cluster5.pth
  output_dir: output/uc_flowers102_rn50_512/perturbation
  batch_size: 512
