
uc_pets_rn50_rn18:
  data_config: config/data.yaml
  dataset: pets
  perturbation_dir: output/uc_pets_rn50/perturbation
  ae_dir: output/uc_pets_rn50/ae

  model: RN18
  normalize: general
  epsilon: 16
  resize_type: img # 'img' or 'noise', img: resize images to fit noise; noise: interpolate noise to fit images

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/pets_rn50_cluster5.pth
  output_dir: output/uc_pets_rn50/rn18


uc_medMnist_rn50_rn18:
  data_config: config/data.yaml
  dataset: medmnist
  perturbation_dir: output/uc_medMnist111111111111111111111·_rn50/perturbation
  ae_dir: output/uc_medMnist_rn50/ae

  model: RN18
  normalize: general
  epsilon: 16
  resize_type: img

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/medMnist_rn50_cluster3.pth
  output_dir: output/uc_medMnist_rn50/perturbation

uc_bloodmnist_rn50_rn18:
  data_config: config/data.yaml
  dataset: bloodmnist
  perturbation_dir: output/uc_bloodmnist_rn50/perturbation
  ae_dir: output/uc_bloodmnist_rn50/ae

  model: RN18
  normalize: general
  epsilon: 16
  resize_type: img

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/bloodmnist_rn50_cluster3.pth
  output_dir: output/uc_bloodmnist_rn50/perturbation

uc_pathmnist_rn50_rn18:
  data_config: config/data.yaml
  dataset: pathmnist
  perturbation_dir: output/uc_pathmnist_rn50/perturbation
  ae_dir: output/uc_pathmnist_rn50/ae

  model: RN18
  normalize: general
  epsilon: 16
  resize_type: img

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/pathmnist_rn50_cluster3.pth
  output_dir: output/uc_pathmnist_rn50/perturbation


uc_pcammnist_rn50_rn18:
  data_config: config/data.yaml
  dataset: pcam
  perturbation_dir: output/uc_pcam_rn50/perturbation
  ae_dir: output/uc_pcam_rn50/ae

  model: RN18
  normalize: general
  epsilon: 16
  resize_type: img

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/pcam_rn50_cluster3.pth
  output_dir: output/uc_pcam_rn50/perturbation

uc_flowers_rn50_rn18:
  data_config: config/data.yaml
  dataset: flowers
  perturbation_dir: output/uc_flowers_rn50/perturbation
  ae_dir: output/uc_flowers_rn50/ae

  model: RN18
  normalize: general
  epsilon: 16
  resize_type: img

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/flowers_rn50_cluster3.pth
  output_dir: output/uc_flowers_rn50/perturbation

uc_organamnist_rn50_rn18:
  data_config: config/data.yaml
  dataset: organamnist
  perturbation_dir: output/uc_organamnist_rn50/perturbation
  ae_dir: output/uc_organamnist_rn50/ae

  model: RN18_gray
  normalize: gray
  epsilon: 16
  resize_type: img

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/organamnist_rn50_cluster3.pth
  output_dir: output/uc_organamnist_rn50/perturbation

uc_flowers102_rn50_rn18:
  data_config: config/data.yaml
  dataset: flowers102
  perturbation_dir: output/uc_flowers102_rn50/perturbation
  ae_dir: output/uc_flowers102_rn50/ae

  model: RN18
  normalize: general
  epsilon: 16
  resize_type: img

  lr: 0.1
  num_epoch: 90
  batch_size: 512

  cluster: output/cluster/flowers102_rn50_cluster5.pth
  output_dir: output/uc_flowers102_rn50/perturbation